### ISSUE TITLE
Code.py seems to be a copy of README.md

### ISSUE THREAD

**Issue by starbuck93** [pjgpetecodes/pico-streamdeck#3]
Looks like commit 408513ce63ca9fb000175ee4bcce858a3a148454 replaced [code.py](https://github.com/pjgpetecodes/pico-streamdeck/blob/main/code.py) with essentially a copy of README.md. Just booted my Pico up for the first time and it looks like going back in time to paste the merged code.py from https://github.com/pjgpetecodes/pico-streamdeck/commit/7de0eab00ef6f1831614697238b37bae672ed84d#diff-9d3abcd877c22876288ec7600c41a6505a704ad3e58caea0de4daa7c596eaaac works fine!

**Comment by pjgpetecodes** [comment]
That's a great call! No idea how that happenned! Thanks! Fixed... !
